### ISSUE TITLE
请问为什么只能在app内打开链接

### ISSUE THREAD

**Issue by dubee2018** [chenfengfeng/ss-vpn#1]

**Comment by chenfengfeng** [comment]
什么叫只能在APP 内打开链接？

**Comment by dubee2018** [comment]
就是只要放到后台vpn就会自动断链

**Comment by dubee2018** [comment]
支持多个IP自动切换
支持自动ping IP地址是否有效
支持只能从APP内打开链接
支持多语言显示
动效算不算?您自己也写了~

**Comment by chenfengfeng** [comment]
你说这个啊，这个跟你现在遇到的切换后台会断开没关系
`支持只能从APP内打开`是指打开VPN服务必须从APP打开，不能从系统的VPN开关来打开

**Comment by dubee2018** [comment]
那为什么我运行demo 只要退出后台就会断开，要哭了

**Comment by chenfengfeng** [comment]
你可以把你觉得有问题的代码提出来看看

**Comment by rongshuizhou** [comment]
我也遇到了这样的问题,就是挂着VPN的图标,但是只要访问别的网页,VPN就断开

**Comment by chenfengfeng** [comment]
@dubee2018 @rongshuizhou 可能是nekit框架，你们如果集成最新的框架，MMDB是需要自己添加数据库，不然会闪退，详情可以看nekit的主页，有说明
