### ISSUE TITLE
PacketTunnelProvider 中 enablePacketProcessing这个变量是干嘛用的？

### ISSUE THREAD

**Issue by THROFHR** [chenfengfeng/ss-vpn#3]
在学习代码过程，看到enablePacketProcessing这个变量，但它一直为false，没有地方去修改它。
那么，很多地方都是 if false 。这里到底是为什么这么设计？

希望有人可以分析一下

**Comment by chenfengfeng** [comment]
这个是为了tun2socks的，正常情况下是不允许使用tcp转发，意味着一些用tcp的APP是无法使用代理的，但是为什么这个一般都是false，是因为这个tun2socks不稳定，容易奔溃
